DELIMITER //

CREATE FUNCTION check_position(pos VARCHAR(3))
RETURNS BOOL NO SQL
BEGIN
  IF pos RLIKE '^[1-9][0-9]*$' THEN
    RETURN TRUE;
  ELSEIF pos IN ('NC', 'DNF', 'DSQ') THEN
    RETURN TRUE;
  ELSE
    RETURN FALSE;
  END IF;
END //

DELIMITER ;
